name: Staging Build & Release

on:
  push:
    branches: ["dev"]


env:
  HELM_REPO: olli-iviet
  APP_NAME: "skills-server-x-viettel"  # <--- CHANGE THIS
  CHART_FOLDER: "skills-server-x-viettel"
  KUBE_NAMESPACE: "service-dev"  # <---- CHANGE THIS
  APP_ENVIRONMENT: "dev"

jobs:
  setup_env:
    name: Setup environment variables
    runs-on: ubuntu-latest
    outputs:
      appName: ${{steps.setenv.outputs.appName}}
      helmRepo: ${{steps.setenv.outputs.helmRepo}}
      chartFolder: ${{steps.setenv.outputs.chartFolder}}
      kubeNamespace: ${{steps.setenv.outputs.kubeNamespace}}
      appEnvironment: ${{ steps.setenv.outputs.appEnvironment }}
    steps:
      - name: set env
        id: setenv
        run: |
          echo "appName=${{ env.APP_NAME }}" >> $GITHUB_OUTPUT
          echo "helmRepo=${{ env.HELM_REPO }}" >> $GITHUB_OUTPUT
          echo "chartFolder=${{ env.CHART_FOLDER }}" >> $GITHUB_OUTPUT
          echo "kubeNamespace=${{ env.KUBE_NAMESPACE }}" >> $GITHUB_OUTPUT
          echo "appEnvironment=${{ env.APP_ENVIRONMENT }}" >> $GITHUB_OUTPUT

  build:
    name: Build dev
    needs: [setup_env]
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: ubuntu-latest
      appName: ${{needs.setup_env.outputs.appName}}
      helmRepo: ${{needs.setup_env.outputs.helmRepo}}
      chartFolder: ${{needs.setup_env.outputs.chartFolder}}
      appEnvironment: ${{needs.setup_env.outputs.appEnvironment}}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  release:
    name: Release dev
    needs: [setup_env, build]
    uses: ./.github/workflows/reusable-release.yml
    with:
      runner: ubuntu-latest
      appName: ${{needs.setup_env.outputs.appName}}
      helmRepo: ${{needs.setup_env.outputs.helmRepo}}
      dockerImage: ${{needs.build.outputs.dockerImage}}
      imageTag: ${{needs.build.outputs.imageTag}}
      chartVersion: ${{needs.build.outputs.chartVersion}}
      namespace: ${{needs.setup_env.outputs.kubeNamespace}}
      environment: ${{needs.setup_env.outputs.appEnvironment}}
      chartFolder: ${{needs.setup_env.outputs.chartFolder}}
      customValues: "values-dev.yaml"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
