name: Reusable Release

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      helmRepo:
        required: true
        type: string
      dockerImage:
        required: true
        type: string
      imageTag:
        required: true
        type: string
      chartVersion:
        required: true
        type: string
      namespace:
        required: true
        type: string
      runner:
        required: true
        type: string
      environment:
        required: true
        type: string
      chartFolder:
        required: true
        type: string
      customValues:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  release:
    name: Deploy & Release
    runs-on: ${{inputs.runner}}
    env:
      EKS_CLUSTER: eks-primary-prod-01
      REGISTRY: 905418372464.dkr.ecr.ap-southeast-1.amazonaws.com
      REGION: ap-southeast-1
      APP_NAME: ${{ inputs.appName }}
      HELM_REPO: ${{ inputs.helmRepo }}
      IMAGE_TAG: ${{ inputs.imageTag }}
      CHART_FOLDER: ${{ inputs.chartFolder }}
      CHART_VERSION: ${{ inputs.chartVersion }}
      DOCKER_IMAGE: ${{ inputs.dockerImage }}
      NAMESPACE: ${{inputs.namespace}}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download chart values
        uses: actions/download-artifact@v3
        with:
          name: chart-values

      - name: Release app in namespace <${{ inputs.namespace }}>
        uses: koslib/helm-eks-action@master
        with:
          command: |
            aws ecr get-login-password --region ${{ env.REGION }} | helm registry login --username AWS --password-stdin ${{ env.REGISTRY }}
            aws --region ap-southeast-1 eks update-kubeconfig --region ap-southeast-1 --name ${{env.EKS_CLUSTER}}
            helm upgrade -i -n ${{ env.NAMESPACE }} ${{ env.APP_NAME }} oci://${{env.REGISTRY}}/${{env.HELM_REPO}}/helm-chart/${{ env.APP_NAME }} --version ${{ env.CHART_VERSION }} --set image.repository=${{env.REGISTRY}}/${{env.DOCKER_IMAGE}} --set image.tag=${{env.IMAGE_TAG}} --set appVersion=${{inputs.appVersion}} --set environment=${{inputs.environment}} --set ghEventNum=${{github.event.number}} --create-namespace --values=${{inputs.customValues}}
